# Project informatio
site_name: LYH Docs
repo_url: https://github.com/lyh-man/MyDocs.git
nav:
  - MyDocs:
    - './tool/mk-docs.md'
  - Tool:
    - './tool/windows-terminal.md'
    - './tool/speed-up-github-access.md'
  - Java:
    - './java/Readme.md'
    - basic:
      - './java/basic/basic.md'
    - core:
      - './java/core/Generics.md'
      - './java/core/Reflection.md'
    - Spring:
#      - Spring:
#        - './java/spring/spring/basic.md'
      - SprintBoot3:
        - './java/spring/springboot3/basic.md'
#        - './java/spring/springboot3/common-operation.md'
  - UML:
    - './uml/basic.md'
    - './uml/class-diagram.md'
    - './uml/plant-uml.md'
  - Network:
    - './network/basic.md'
    - './network/tcp.md'
  - WXMiniProgram:
    - Guide:
      - './wx-mini-program/basic.md'
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.path
    - navigation.top
