site_name: My Docs
repo_url: https://github.com/lyh-man/MyDocs.git
nav:
  - Home: 'index.md'
  - Tool:
    - './tool/mk-docs.md'
    - './tool/windows-terminal.md'
    - './tool/plant-uml.md'
    - './tool/speed-up-github-access.md'
  - Java:
    - './java/basic/basic-knowledge.md'
  - UML:
    - './uml/basic.md'
    - './uml/class-diagram.md'
theme:
  name: material