site_name: My Docs
repo_url: https://github.com/lyh-man/MyDocs.git
nav:
  - Home: 'index.md'
  - Tool:
    - './tool/MkDocs.md'
    - './tool/windows-terminal.md'
    - './tool/PlantUML.md'
    - './tool/speed-up-github-access.md'
  - Java:
    - './Java/basic/basic-knowledge.md'
  - UML:
    - './UML/basic.md'
    - './UML/class-diagram.md'
theme:
  name: material