# Project informatio
site_name: LYH Docs
repo_url: https://github.com/lyh-man/MyDocs.git
nav:
  - MyDocs:
    - './tool/mk-docs.md'
  - Tool:
    - './tool/windows-terminal.md'
    - './tool/speed-up-github-access.md'
  - Java:
    - './java/basic/basic-knowledge.md'
  - UML:
    - './uml/basic.md'
    - './uml/class-diagram.md'
    - './uml/plant-uml.md'
  - WXMiniProgram:
    - Guide:
      - './wx-mini-program/basic.md'
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.path
    - navigation.top
